import Head from "next/head";

export default function SEO() {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta property="og:title" content="InspectGPT" />
      <meta
        property="og:description"
        content="Identify GPT-generated text on any web page!"
      />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="https://inspectgpt.com/" />
      <meta property="og:image" content="https://..." />

      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
