import Head from "next/head";
import Image from "next/image";

import logo from "../public/inspect-gpt-dark.svg";

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-full flex flex-col items-center">
        <header className="w-full h-20 flex justify-between items-center px-32 box-border">
          <Image src={logo} alt={""} />
        </header>
        <section className="flex flex-col gap-10 pt-36 pb-24 items-center">
          <h1 className="text-gpt-500 text-6xl font-bold">Saved Pages</h1>
        </section>
        <section className="pb-36 flex flex-col gap-2 w-5/12">
          <div className="px-6 flex items-center justify-between w-full">
            <p className="text-gpt-200/80">Website Title</p>
            <p className="text-gpt-200/80">GPT probability</p>
          </div>
          <div className="border border-gpt-200/20 bg-gpt-100 rounded-full px-6 py-2 flex items-center justify-between w-full">
            <p className="font-semibold text-gpt-500">
              Futurism - This Site Detects Whether Text Was Written by a Bot
            </p>
            <p className="font-bold text-green-600">31% GPT</p>
          </div>
          <div className="border border-gpt-200/20 bg-gpt-100 rounded-full px-6 py-2 flex items-center justify-between w-full">
            <p className="font-semibold text-gpt-500">
              Futurism - This Site Detects Whether Text Was Written by a Bot
            </p>
            <p className="font-bold text-green-600">31% GPT</p>
          </div>
          <div className="border border-gpt-200/20 bg-gpt-100 rounded-full px-6 py-2 flex items-center justify-between w-full">
            <p className="font-semibold text-gpt-500">
              Futurism - This Site Detects Whether Text Was Written by a Bot
            </p>
            <p className="font-bold text-green-600">31% GPT</p>
          </div>
        </section>
      </main>
    </>
  );
}
